apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: 891377089515.dkr.ecr.ap-south-1.amazonaws.com/application-repo:latest
        ports:
        - containerPort: 5000